application: pascaloblog
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /3rdparty
  static_dir: static/3rdparty

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /admin/.*
  script: main.py
  login: admin

- url: .*
  script: main.py

